prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/lists/nav_top.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/nobody.sql
@@application/shared_components/security/authorizations/is_developer.sql
@@application/shared_components/security/authorizations/is_administrator.sql
@@application/shared_components/security/authorizations/is_active_user.sql
@@application/shared_components/security/app_access_control/is_administrator.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/init_globals.sql
@@application/shared_components/logic/application_processes/init_translations.sql
@@application/shared_components/logic/application_processes/init_filters.sql
@@application/shared_components/logic/application_items/g_today.sql
@@application/shared_components/logic/application_items/g_today_label.sql
@@application/shared_components/logic/application_items/g_tomorrow.sql
@@application/shared_components/logic/application_items/g_version.sql
@@application/shared_components/logic/application_items/g_yesterday.sql
@@application/shared_components/logic/application_items/t_button_refresh.sql
@@application/shared_components/logic/application_items/t_button_submit.sql
@@application/shared_components/logic/application_items/t_page_name.sql
@@application/shared_components/logic/application_items/t_page_title.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/lov_core_events_event_id_event_name.sql
@@application/shared_components/user_interface/lovs/lov_core_flags_name_value.sql
@@application/shared_components/user_interface/lovs/lov_core_languages.sql
@@application/shared_components/user_interface/lovs/lov_core_pages_page_id_page_name.sql
@@application/shared_components/user_interface/lovs/lov_core_roles_role_id_role_name.sql
@@application/shared_components/user_interface/lovs/lov_core_schedules.sql
@@application/shared_components/user_interface/lovs/lov_core_templates.sql
@@application/shared_components/user_interface/lovs/lov_core_users_active_user_id_user_id.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/standard_q.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/navigation_bar_q.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/theme_display_points.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/apex_accounts.sql
@@application/shared_components/security/authentications/open_door_testing_only.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00100.sql
@@application/pages/page_00900.sql
@@application/pages/page_00901.sql
@@application/pages/page_00902.sql
@@application/pages/page_00905.sql
@@application/pages/page_00910.sql
@@application/pages/page_00915.sql
@@application/pages/page_00920.sql
@@application/pages/page_00925.sql
@@application/pages/page_00940.sql
@@application/pages/page_00945.sql
@@application/pages/page_00950.sql
@@application/pages/page_00951.sql
@@application/pages/page_00952.sql
@@application/pages/page_00955.sql
@@application/pages/page_00960.sql
@@application/pages/page_00961.sql
@@application/pages/page_00965.sql
@@application/pages/page_00969.sql
@@application/pages/page_00970.sql
@@application/pages/page_00990.sql
@@application/pages/page_00995.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_install_tables.sql
@@application/deployment/install/install_install_views.sql
@@application/deployment/install/install_install_sequences.sql
@@application/deployment/install/install_install_packages.sql
@@application/deployment/install/install_install_data.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
