CREATE OR REPLACE TRIGGER logon_init
AFTER LOGON ON SCHEMA
BEGIN
    DBMS_SESSION.SET_NLS('NLS_LANGUAGE',            '''ENGLISH''');
    DBMS_SESSION.SET_NLS('NLS_TERRITORY',           '''CZECH REPUBLIC''');
    DBMS_SESSION.SET_NLS('NLS_NUMERIC_CHARACTERS',  '''. ''');
    DBMS_SESSION.SET_NLS('NLS_DATE_FORMAT',         '''YYYY-MM-DD HH24:MI:SS''');
    DBMS_SESSION.SET_NLS('NLS_TIME_FORMAT',         '''HH24:MI:SSXFF''');
    DBMS_SESSION.SET_NLS('NLS_TIMESTAMP_FORMAT',    '''YYYY-MM-DD HH24:MI:SSXFF''');
    DBMS_SESSION.SET_NLS('NLS_TIME_TZ_FORMAT',      '''HH24:MI:SSXFF TZR''');
    DBMS_SESSION.SET_NLS('NLS_TIMESTAMP_TZ_FORMAT', '''YYYY-MM-DD HH24:MI:SSXFF TZR''');
    DBMS_SESSION.SET_NLS('NLS_SORT',                '''BINARY_AI''');
    DBMS_SESSION.SET_NLS('NLS_COMP',                '''LINGUISTIC''');
    --

    --ALTER SESSION SET TIME_ZONE = '+02:00';

END;
/

